# GitHub Ruleset for main and dev branches
# Enforces code review best practices, but allows repository owner to merge their own changes if needed

rules:
  - name: Require code review for main and dev
    conditions:
      branch:
        - main
        - dev
    enforcement: true
    rules:
      pull_request:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: false
        require_review_request: true
        restrict_merges_to_admins: false
        allow_owner_to_merge: true
        require_status_checks: false
        require_conversation_resolution: true
        require_linear_history: true
        block_force_pushes: true
        block_deletions: true
